### PR TITLE
Add workflow to automatically update assets via `nova-kit/nova-packages-tool`

### PR DESCRIPTION
**Pull request by crynobone**
* `laravel-nova` will be served via external `window.LaravelNova` and no longer requires asset rebuild whenever `mixins` contains any changes.
* `nova-kit/nova-packages-tool` will bump new version after Nova made any minor/patch release before user can received the updated version.
* smaller dist files since it no longer build all `mixins`.

### CODE REVIEW

**Comment by dinandmentink** [comment]
Thanks for the PR. Will have a look tomorrow.

**Comment by dinandmentink** [comment]
I see still new commits, is this ready for review?

**Comment by crynobone** [comment]
Yes its ready.

**Comment by dinandmentink** [comment]
Thanks for the PR @crynobone! It seems to work. Open to merging this but still have a question.

I'm still not entirely sure why this change is necessary. I always perform a build before releasing. Could you please describe the advantage of using nova-packages-tool as an external dependency? It gives me an extra dependency to monitor.

**Comment by crynobone** [comment]
> I always perform a build before releasing.

Currently, you should also always build whenever Nova releases any minor release because it may contain changes that would be incompatible with the previous version. 

The `nova-packages-tool` will take over these changes, your user will only get the latest compatible Nova based on the `nova-packages-tool` installed.

**Comment by dinandmentink** [comment]
Thanks for the explanation. I'll work towards releasing this.

**Review by dinandmentink — APPROVED** [review]

**Pull request merged**
